README.md
`run simpleTest` doesn't work :)
=> update simplest irb use in readme

Expecto/Expecto.fs
Current behavior: 
```
λ .\Expecto.Tests\bin\Release\Expecto.Tests.exe --list-tests
some different benchmarks/md5 versus sha256
run
all focused tests/pending
all focused tests/focused
all focused tests/ignored by attribute
all/basic
all/using computation expression
all/string comparison/string equal
all/string comparison/fail - different length
all/string comparison/fail - different content
all/sumTestResults/passed
all/sumTestResults/failed
all/sumTestResults/exn
all/sumTestResults/duration
all/TestResultCounts/plus/Passed
all/TestResultCounts/plus/Ignored
all/TestResultCounts/plus/Failed
all/TestResultCounts/plus/Errored
all/TestResultCounts/plus/Time
all/TestResultCounts/ToString
all/Exception handling/Expecto ignore
all/Setup & teardown/1
all/Setup & teardown/2
timeout/Setup & …
```
=> Implement filtering

README.md
=> add to performance and testSequenced docs

Expecto.Tests/FocusedTests.fs, Expecto.Tests/Main.fs, Expecto/Expecto.fs, Settings.FSharpLint
Fot the CI server we want to have an option to make the build fail if focused tests exist.
closes #28
=> make the test runner fail if focused tests exist

Expecto/Expecto.fs
[12:26:47 INF] EXPECTO?! Summary...
Passed:
debug-config/sound check - can take screenshot
debug-config/search/can go to search
Ignored:
Failed:
Errored:
will be:
[12:26:47 INF] EXPECTO?! Summary...
Passed: 2
debug-config/sound check - can take screenshot
debug-config/search/can go to search
Ignored: 0
Failed: 0
Errored: 0
=> Add counts to summary

Expecto/Expecto.fs
=> Trace assembly version

Expecto/Expecto.fs
@haf  @Krzysztof-Cieslak 
Fixes problems with me stomping all over the config.
The summary still didn't come through. I had to change logger.info to logger.logWithAck.
=> fixes #53 summary bug

Expecto.Tests/Expecto.Tests.fsproj, Expecto.Tests/SummaryTests.fs, Expecto/Expecto.fs, build.fsx, paket.lock
This is the current situation:
I hope line breaks are now ok
=> Fix line breaks

Expecto.Tests/Tests.fs, Expecto/Expect.fs
#63 
CC: @Krzysztof-Cieslak @haf
=> #63 change distribution error msg

Expecto.Tests/BenchmarkDotNet.fs, Expecto.Tests/FocusedTests.fs, Expecto.Tests/FsCheckTests.fs, Expecto.Tests/Prelude.fs, Expecto.Tests/Tests.fs, Expecto/Expecto.fs, appveyor.yml
appveyor.yml is working now and passing tests if you want to set it up and add a badge.
=> assertTestFails as tests, more options for parallel-workers, fix failing tests

Expecto.FsCheck/FsCheck.fs, Expecto.Tests/Expecto.Tests.fsproj, Expecto.Tests/FsCheckTests.fs, Expecto.Tests/Tests.fs, Expecto/Expect.fs, Expecto/Expecto.fs, README.md
Focused test property takes StdGen. Will do docs if ok.
=> FsCheck messages, focus and pending methods, closes #68

Expecto.Tests/FocusedTests.fs, Expecto/Expecto.fs
Also added two tests for parallel = false.
Could not reproduce the hanging though.
=> fixes #84 parallel bug

Expecto/Expect.fs
Add friendly messages for isTrue and isFalse. Also reword notEqual.
=> Default message texts for isTrue and isFalse

Expecto.Tests/Tests.fs, Expecto/Expect.fs
As mentioned in Issue #89 
cc: @adamchester and @haf
=> #89 improve sequence equal message

Expecto.Tests/Tests.fs, Expecto/Expect.fs
As mentioned in issue: #92 
CC: @haf
=> Issue 92 float assertions

README.md
Update readme to include new functions.
#92 #93 
CC: @haf
=> #92 update readme

Expecto.Tests/Tests.fs
Still failing! I've removed the reader writer locking and reduced the sleep. Hoping its only the number of workers and a small sleep needed.
=> remove reader writer locks

Expecto.Tests/Tests.fs, Expecto/Expecto.fs
4 tests added to test run with filters.
=> Fix missing filter fixes #99

README.md
=> Remove "framework" from readme and GitHub header

README.md
=> 117 update readme

Expecto.Tests/Tests.fs, Expecto/Expect.fs, Expecto/Flip.Expect.fs, README.md
#132 
- isRegexMatch
- isNotRegexMatch
=> #132 ismatch and is not match

Expecto.Tests/Tests.fs, Expecto/Expect.fs, Expecto/Flip.Expect.fs, README.md
#156 , continue of #157 
`allEqual` function.
CC: @haf
=> #156 add allequal method

README.md
Sample added to test thing using custom generated sample data.
=> Updated with sample of custom user data

README.md
Since Expecto.Template has stable version it could be installed without specifying a concrete version.
@haf
=> Update information about how to install Expecto Template

Expecto/Expecto.netcore.fsproj, paket.dependencies, paket.lock
Update Mono-Cecil to 0.10.0-beta7
CC: @AnthonyLloyd
=> Update Mono.Cecil to 0.10.0-beta7

Expecto/Expecto.fs
A simple way to implement #223 without too many changes to the code.
=> Allow specifying log name at command line

paket.dependencies, paket.lock
Update [Mono.Cecil](https://www.nuget.org/packages/Mono.Cecil/0.10.0)
CC: @AnthonyLloyd
=> update mono.cecil to 0.10.0

Expecto.BenchmarkDotNet/Expecto.BenchmarkDotNet.fsproj, Expecto.FsCheck/Expecto.FsCheck.fsproj, Expecto.Hopac/Expecto.Hopac.fsproj, Expecto/Expecto.fsproj
https://github.com/haf/expecto/issues/250
=> add sourcelink support

Expecto.Tests/Tests.fs, Expecto/Expect.fs
https://github.com/haf/expecto/issues/252
=> comparison of affine (ephemeral) sequence

Expecto.TestResults/CSharp.fs, Expecto.TestResults/Library.fs
Gitlab supports JUnit Xml: https://docs.gitlab.com/ee/ci/junit_test_reports.html
=> add JUnit-like summary file

Expecto.Tests/Tests.fs, Expecto/Expect.fs
Related to #276 
Message looks like this:
CC: @haf
=> #276 should works right now

README.md
Small PR to _beautify_ the `README.md` header section.
- Centered content.
- Added licence.
- Added F# percentage badge :D
Happy to iterate on any feedback or requested changes.
=> Beautify Readme.md Header.

Expecto/Expect.fs, Expecto/Flip.Expect.fs, README.md, RELEASE_NOTES.md
Acts like Expect.wantOk but for the Error case.
=> Introduce Expect.wantError

Expecto/Expecto.Impl.fs
=> list focused tests

README.md
I saw that you mentioned this in your video explicitly. Thought it makes sense to have the README consistent with that. Also this tripped me when I copy and pasted this :)
=> prevent globbing

README.md
Fixes: #407
I take a look at all examples in Readme.md and fix all of them which seems to be wrong.
CC: @haf
=> #407 update readme examples

README.md
Fixed wrong command snippet in README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/haf/expecto/417)
=> Fix wrong command snippet

Expecto.Tests/Tests.fs, Expecto/Expecto.fs, README.md
This PR introduces the `testFixtureAsync` and `testFixtureTask` functions.
=> Add testFixtureAsync and testFixtureTask

Expecto.Tests.CSharp/Tests.cs, Expecto.Tests/Tests.fs, Expecto/CSharp.fs, Expecto/Expecto.Impl.fs, Expecto/Expecto.fs
This PR removes all the deprecated code laying around the codebase. This is a preparation for a new release.
This extends #383.
=> Remove deprecated code

Expecto.Tests/Tests.fs, Expecto/Expect.fs, Expecto/Flip.Expect.fs, README.md
Async versions of the `throws` functions.
=> Add throwsAsync, throwsAsyncT, and throwsAsyncC

README.md
=> Correct command to install dotnet template

Expecto.Tests/Tests.fs, Expecto/Expecto.fs
Added functions per discussion on #500. Sorry, I forgot about this one!
=> Added testParamAsync and testParamTask

Expecto/Expecto.Impl.fs
refs https://github.com/haf/expecto/issues/517
Just having a go at the suggestion in https://github.com/haf/expecto/issues/517#issuecomment-2667402585
I've tried a local build with a couple of my own projects in Visual Studio 2022 and it seems to still work and be a tad faster, but the test discovery only takes a few seconds for those anyway so it's a small difference.
=> Cache the collected type information in getSourceLocation

Expecto/Expecto.Impl.fs
[refs 518](https://github.com/haf/expecto/pull/518#issuecomment-2764615318)
=> Cache the collected type information in getSourceLocation (#518)
