haf/expecto

- Expecto.Tests/Expecto.Tests.fsproj
- Expecto.Tests/FocusedTests.fs
- Expecto.Tests/Tests.fs
- Expecto/Expecto.fs
- Gemfile.lock
- README.md
I'm sorry that this PR is so big, but is the only way it makes sense.
Only thing that is not covered by tests is discovery of tests marked with *FTestsAttribute* - as will mess up the current tests. I tested manually and it's working :) . I was thinking on creating a new project for automate testing this particular issue.
This PR is covering the issue #7
> Added support for focusing and pending tests

- Expecto.Tests/Prelude.fs
- Expecto.Tests/Tests.fs
- Expecto/Expect.fs
Right now it uses same algorithm as Streams and Sequences equality. 
Two questions:
1. Is it enough? Or should we scan whole string for differences instead of failing on 1st different character.
2. Should it be part of equals or moved to different function just as `streamsEqual` and `sequenceEqual`, or maybe other way round - merge `streamsEqual` and `sequenceEqual` into `equals` so there is smaller API surface for user.
> Add better messages for string equality

- .vscode/launch.json
- .vscode/tasks.json
- Expecto.Tests/Tests.fs
- Expecto/Expecto.fs
It'll be useful for Ionide (and maybe other editors) integration.
PR also adds VSCode configuration letting build and debug `Expecto.Tests` project.
> Add parameter to list tests in console

- Expecto.Tests/Tests.fs
- Expecto/Expecto.fs
Add parameter which allows user to specify exact list of tests to run.
Current behavior:
```
λ .\Expecto.Tests\bin\Release\Expecto.Tests.exe --run all/basic "all/using computation expression" "all/sumTestResults/passed"
[16:33:57 INF] EXPECTO? Running tests...
[16:33:57 INF] EXPECTO! 3 tests run in 00:00:00.0476590 - 3 passed, 0 ignored, 0 failed, 0 errored.
```
> Add run parameter

- Expecto.Tests/Tests.fs
- Expecto/Expect.fs
- README.md
1. Adds following assertions:
* `stringEnds`
* `strignHasLength`
* `sequenceStarts`
* `isAscending`
* `isDescending`
2. Fixes bug in string and sequence equals when actual was longer than expected
3. Adds to readme new assertions, and changes in parameters done as part of previous PRs.
> Add more assertions

- Expecto.Tests/FocusedTests.fs
- Expecto.Tests/Prelude.fs
- Expecto.Tests/Tests.fs
- Expecto/Expecto.fs
- README.md
Adds option to print out additional summary after all tests are run if `--summary` parameter is provided.
```
λ .\Expecto.Tests\bin\Release\Expecto.Tests.exe --filter-test-list expectations --summary                             
[23:08:49 INF] EXPECTO? Running tests...                                                                              
...
[23:08:49 INF] EXPECTO! 23 tests run in 00:00:00.1124037 - 23 passed, 0 ignored, 0 failed, 0 errored.                 
[23:08:49 INF] EXPECTO?! Summary...                                                                                   
Passed:                                                                                                               
timeout/expectations/raise/pass …
```
> Add summary

- Expecto.Tests/Prelude.fs
- Expecto/Expecto.fs
- Rakefile
Fixes summary aggregation. Which should fix both #24 and #23.
Current output for Expecto.Sample:
```
λ .\Expecto.Sample.exe --summary
[16:22:44 INF] EXPECTO? Running tests...
[16:22:44 ERR] samples/should fail failed in 00:00:00.0002488.
I should fail because the subject is false.
D:\Programowanie\Projekty\expecto\Expecto.Sample\Expecto.Sample.fs(14,1): Expecto.Sample.tests@14-2.Invoke(Unit _arg2)
[16:22:44 INF] EXPECTO! 2 tests run in 00:00:00.0556704 - 1 passed, 0 ignored, 1 failed, 0 errored.
[16:22:44 INF] EXPECTO?! Summary...
Passed:
samples/universe exists
Ignored:
Failed:
samples/should fail
Errored:
λ $lastExitCode
1
```
Sorry for introducing this bug in first place :-(
> Fix sumTestResults

- Expecto.Tests/Tests.fs
- Expecto/Expect.fs
#3 
Show expected/actual string in SequenceEquals fail message.
> String diff support #3

- Expecto.Tests/Tests.fs
- Expecto/Expect.fs
- README.md
I saw that in Expect are available following methods:
* _contain_
* _sequenceEqual_
But the first one looks if sequence contains specific element. Second one checks if sequence is equal to another sequence (position in a list is taken into account)
So maybe it is a good idea to add containsAll method which would look if given sequence contains all elements from a second sequence (not more, not least) and not looking for their position in sequence?
So following tests should return "pass" result:
If test fails following errors will be shown:
> Add containsAll method to expecto

- .gitignore
- Expecto/Expecto.fs
This will allow users to supply their own tests and still use the command line args
> Create a new function runTestsWithArgs

- README.md
@haf since you don't seem to use release_notes.md I have the paragraph here:
* This release provides a `runTestsWithArgs` function which runs the passed tests and also overrides the passed `ExpectoConfig` with the command line parameters.
* Expecto now accepts the command line argument `--fail-on-focused-tests`, which checks if focused tests exist. This parameter can be set in build scripts and allows CI servers to reject commits that accidentally included focused tests.
> Docs for --fail-on-focused-tests and runTestsWithArgs

- Expecto.BenchmarkDotNet/Expecto.BenchmarkDotNet.fsproj
- Expecto.Tests/BenchmarkDotNet.fs
- Expecto.Tests/Expecto.Tests.fsproj
- Expecto.Tests/FocusedTests.fs
- Expecto.Tests/Prelude.fs
- Expecto.Tests/SummaryTests.fs
- Expecto.Tests/Tests.fs
- Expecto/Expecto.fs
- Expecto/Expecto.fsproj
- Expecto/paket.references
- paket.dependencies
- paket.lock
Adds ability to print out test location (source file, line of code). Still work in progress. 
Cons:
* As far as I understand there are certain limitations (it's based on Pdb files so won't work in release configs etc)
* It adds a bit of complexity and additional dependency (`Mono.Cecil`)
Pros:
* It will allow much better editor integrations. (For example in VSCode in watch mode marking which tests are passing and which not)
> Add tests' source file location 

- Expecto.Tests/Tests.fs
- Expecto/Expect.fs
- Expecto/Expecto.fs
- README.md
@haf,
Here is something I find useful for your consideration. It allows you to compare floats that are either large or small by combining an absolute and relative accuracy.
Its along the lines of https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.isclose.html but better :).
You may want to look to deprecate `Expect.floatEqual`
> add Expect.floatClose with better accuracy test

- Expecto.Tests/Prelude.fs
- Expecto.Tests/Tests.fs
- Expecto/Expect.fs
- Expecto/Expecto.fs
- Expecto/Expecto.fsproj
Hopefully the style is ok.
I think for LF vs CRLF you need a .gitattributes file.
I think ultimately there must be a better way to handle sync/async logging. Needs to be able to be switched  from async flush to manual flush.
> fix mutable sync/async logging and support async tests

- Expecto/Expecto.fs
- README.md
Also:
- minor change to fasterThan wording
- small change to parallelLimit (only need List.length workers if max is too high)
> async docs, async pending/focused, closes #2

- Expecto/Expecto.fs
so that it doesn't become an old broken link soon.
Now that Expecto provides the source location (🎉), we will remove the original code that discovered source location from the Expecto.VisualStudio.TestAdapter package.
> Change comment to a commit-permalink,

- Expecto.Tests/Tests.fs
Can't reproduce on my machine with a stress test. Build machine must be quite different.
Its down to trying to create a deadlock in two tests. Not so easy to guarantee.
I've put up the sleep time in the deadlock from 10ms to 100ms. I think this should do the trick.
Its not an issue with the functionality just the ability to create a failing test.
Let me know if you see it again.
> increase sleep in deadlock

- Expecto/Expecto.fs
- build.fsx
Spotted a bug with the printing of version getting mixed up while using Expecto.
Also add FAKE Target to make paket.local easy as follows:
nuget Expecto -> git file:///C:\Users\Ant\src\expecto master build:"build.cmd CreateNuGets", Packages: /build/pkg/
> minor --version bug fix and paket.local support

- Expecto.Sample/Expecto.Flip.Sample.fs
- Expecto.Sample/Expecto.Sample.fsproj
- Expecto/Expect.fs
- Expecto/Expecto.fsproj
- Expecto/Flip.Expect.fs
Proposal for #107
The main thing I'm concerned about are the isGreaterThan & co, and maybe the contains; others seem to read well.
Note that I renamed `format` into `message` as that parameter is not a format (from my understanding) but the failure message. I can rename those in the plain module or make them `format` here.
> Add a Expecto.Flip.Expect module

- README.md
Small typo, which leads to an exception, because "Hello **w**orld" is not equal to "Hello **W**orld".
-->  Expecto.AssertException: The string should equal.
> fixed typo in first example in Readme

- Expecto/Expecto.fs
> Better name formatting for TeamCity

- Expecto/Expect.fs
- Expecto/Flip.Expect.fs
- README.md
These test the Result type from F# 4.1, so they will only be available in Expecto versions 5.x and above.
This will fix #62.
> Add isOk and isError expectations

- Expecto.Tests/Tests.fs
- Expecto/Expect.fs
- Expecto/Flip.Expect.fs
- README.md
#156 
`exists` function. 
`all` function, without `delta/diff function`
Error msg for `all` looks like this:
Is it ok? When `delta/diff function` would be implemented it could be changed to `Element at index %d which is equal to %A, has following difference %A"?
CC: @haf
> #156 add exists function

- Expecto/Expect.fs
- Expecto/Expecto.fs
- Expecto/Performance.fs
Remove all usages of List/Seq nth and replace them by List/Seq item since nth is deprecated.
So we don't see these warnings:
`Note: In F# 3.x, nth is defined with inconsistent signatures for Array and List. The proposal above replaces nth by item and would eventually deprecate nth (with a message to say 'please use Seq.item'. It also adds a corresponding tryItem. Both item and tryItem would take the integer index as the first parameter.` [source](https://visualfsharp.codeplex.com/wikipage?title=Status)
CC: @haf
> Use Seq/List item instead of Seq/List nth

- Expecto/Expecto.fs
Fix #162.
Wasn't sure if this makes sense for stress printer, so I leave it unchanged.
> SummaryPrinter and summaryWithLocationPrinter update current printer instead of replacing it.

- Expecto.Tests/Tests.fs
- Expecto/Expect.fs
Hello, please review this PR.
It seems that now ```Expect.throws``` does not fail test when exception is not raised
> Expect.throws should fail when exception is not raised

- Expecto.Tests.CSharp/Tests.cs
- Expecto/Expecto.fs
Reason:
The following code compiles and runs, but does not what I expected it to:
```C#
[FTests]
public static Test blah =
Runner.TestList("Test", new[]{ Runner.TestCase("TestCase", async () =>
{
await Task.FromException(new Exception("FAIL"));
})});
```
It used the ``Action`` overload, so the exception is thrown on the threadpool, where no-one cares.
Now it _should_ prefer the ``Func<Task>`` overload and correctly fail the test.
Note: I can't build it locally, so let's see what the CI says.
> add Func<Task> overloads to the C# api

- Expecto.netcore/Expecto.netcore.fsproj
Verified that the build does the expected thing on MacOS.  Fixes #191 
```
3:17 $ monodis --assembly Expecto.dll
Assembly Table
Name:          Expecto
Hash Algoritm: 0x00008004
Version:       5.0.0.0
Flags:         0x00000000
PublicKey:     BlobPtr (0x00000000)
Zero sized public key
Culture:
```
> fixes #191

- Expecto.netcore/Expecto.netcore.fsproj
The `Expecto.Flip.Expect` module is missing in the .NET Standard version.
> Add Expecto.Flip.Expect module to .NET Standard version

- Expecto/Expecto.fs
The pronoun "his" feels wrong in English for an impersonal object like a test; "its" is the right pronoun here.
> Minor grammar fix

- Expecto/Expecto.fs
https://github.com/haf/expecto/issues/142
Prints nearest common ancestor list name in default printer summary log
If only 1 test, prints name or list name
If no common ancestor for summary, prints "miscellaneous"
> default printer log with list name

- Expecto.Tests.CSharp/Tests.cs
- Expecto/Expecto.fs
As the C# sample project shows, it is already possible without too much fuzz to define Tests in C#.
But without the F# ``with`` expression, it is actually pretty hard to update the config.
This adds .With* methods, and also adds a way for C# code to define a Printer.
> ExpectoConfig: add C# compatible With* methods / Logging: add Task based Interface

- Expecto.Tests/Tests.fs
- Expecto/Expect.fs
- Expecto/Expecto.fs
- Expecto/Expecto.fsproj
- Expecto/Logging.fs
- Expecto/Progress.fs
- README.md
- build.fsx
This PR aims to resolve #256 #249 #248 #230 #190 #161 #152 #147
> console work

- Expecto/Expecto.fs
fixes https://github.com/haf/expecto/issues/269
after:
> unwrap AggregateExceptions with a single inner exception

- Expecto.Tests/Tests.fs
- Expecto/Expect.fs
In case when the function provided to `throwsT` threw no exception a misleading assert message was shown mentioning an `AssertException`.
The added test would fail with the following message:
> Should have failed with message containing: "Expected f to throw." but failed with "
> Should throw null arg. Expected f to throw an exn of type System.ArgumentNullException, but one of type Expecto.AssertException was thrown."
> Fix `throwsT` message on no exception.

- Expecto.TestResults/CSharp.fs
- Expecto.TestResults/Library.fs
- Expecto.Tests.CSharp/Tests.cs
because gitlab can't yet handle errors.
--------------
see https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/parsers/junit.rb#L45-52
and issue https://gitlab.com/gitlab-org/gitlab-ce/issues/51087
This also means that skipped tests aren't surfaced anywhere and are treated as successfull. Which isn't great, but I guess they didn't fail ...
-------
I know you _just_ pushed a release yesterday, but for when do you plan the next?
Asking whether I should wait for official, or just build a nupkg myself.
Thank you!
> junit report: add option to treat errors like failures 

- Expecto.Hopac.Tests/Tests.fs
- Expecto.Hopac/Expecto.Hopac.fs
This more closely aligns Expecto's `TestJobBuilder` to Hopac's [JobBuilder](https://github.com/Hopac/Hopac/blob/master/Libs/Hopac/Hopac.fs#L2176-L2203).
Adds tests to cover the additional binds in `testJob`.
> Aligns TestJobBuilder closer to Hopac's JobBuilder

- Expecto/Expecto.fs
> Report duplicated test names via printer

- README.md
The `Logary.Targets`  namespace seems required to get `LiterateConsole` in scope.
> update logary sample

- Expecto/Expecto.fs
Related to #348 . 
I have 2 questions:
1. All places that should be changed are covered here?
2. Checking if `InnerException` is right, or we prefer ` <> null`?
CC: @haf
> Get inner message from exception

- Expecto.Tests/Tests.fs
- Expecto/Expect.fs
- Expecto/Expecto.fs
- Expecto/Flip.Expect.fs
They act like `isSome`/`isOk`, but also return the expected value.
Also, `testName` is now a genericvalue (to make it feel more like a value), and `throwsT` requires an explicit type argument.
The former is a breaking change (that is justified by the major version bump), and the latter is technically a breaking change as well, but more of an enforcement of how the function should have been used.
> Introduce Expect.wantSome and Expect.wantOk.

- Expecto/Expecto.Impl.fs
- Expecto/Expecto.fs
Fixes: #378
The wrong parameter was passed in Expecto.fs lines 523/524. The changes were introduce in this [commit](https://github.com/haf/expecto/commit/b168ca3e186b7c7bf5e4ac36fc99ec558aee2126) because of a rename from `tests` to `fTests` :(. 
CC: @haf
> #378 pass filtered tests instead of not filtered.

- Expecto/Expecto.Impl.fs
- Expecto/Expecto.fs
- README.md
- All usages of `deprecated` `runTestsXXX` removed from README.md (except line 153),
- All occurrences of `depricated` renamed to `deprecated`,
- Added comments with `deprecation` info to the following:
- `runTestsWithCancel`
- `runTests`
- `runTestsWithArgsAndCancel`
- `runTestsWithArgs`
- `runTestsInAssemblyWithCancel`
- `runTestsInAssembly`
@haf
> #360 - usage of deprecated functions in README.md

- Expecto/Expect.fs
When comparing small values the default `%f` formatter will not show a difference between actual and expected even when the test fails. Changed to `%.20g` to print the full precision of the value and automatically select the most compact representation.
> Improved error msg of floats in floatClose

- .paket/Paket.Restore.targets
- Expecto.Tests/Tests.fs
- Expecto/CSharp.fs
- Expecto/Expecto.Impl.fs
- Expecto/Expecto.fs
- Expecto/Helpers.fs
- Expecto/Logging.fs
- RELEASE_NOTES.md
following PR to enhancement #392  
Proposed changes and usage:
- `--list-tests` - lists all tests as before
- `--list-tests focused` - lists focused tests only
- `--list-tests pending focused` - lists pending and focused tests only
- added a "state char" before test name (N, P, F). It is hidden as before, if none of listed tests are focused or pending (not the case in Expecto.Tests)
```
P pending_test.case.one 
F focused_test.case.two
N normal_test.case.three 
```
> add options to list focused tests

- Expecto.Diff/Library.fs
Fixes https://github.com/haf/expecto/issues/419
I tested this by running `dotnet run --project Expecto.Sample --framework net5.0` in this repo.
First, the default output for comparison:
Notes:
- Expected comes first, then actual.
- Expected is in green, actual in red.
Then, the `Expecto.Diff` output:
Notes:
- The Actual/Expected _headings_ are flipped compared to the default formatting.
- The actual/expected _text_ are still in the same order as the default formatting. In other words, the headings are for the wrong text.
- The colors are flipped compared to the default formatting.
- Also note how the first heading and `{A =` is blue, while it should be white.
Finally, the output with this PR:
Notes:
- Fixed the headings so Expected comes first, just like in the default formatting. And now …
> Fix flipped/mixed up Expecto.Diff formatting

- README.md
While browsing the documentation I noticed that the "Testing Hello world" link in the Readme doesn't work correctly. This small PR fixes this.
I also verified [doctoc](https://github.com/thlorenz/doctoc) has a problem with quotes but it generates the TOC correctly so I'm not sure what went wrong [there](https://github.com/haf/expecto/commit/58436fdc7f0f10447efabb56a614ff64c60378f2).
> fix Testing "Hello world" link

- paket.dependencies
I got interested in this because of #424 -- without F# 5, Expecto can't test any
assemblies that use F# 5 string interpolation. Since I opened that issue, F# 6
has come out. Might as well use that!
My only concern here is testing. Running the test suite, I see two reported failures, both having to do with the performance of SHA256 vs MD5. However, both of those tests also fail locally on main for me, so I don't think it's related to this change. 
Thanks for the lovely testing library!
Closes #424
> Update F# Version to most current (6)

- README.md
I changed dotnet core to dotnet and updated the version number in one example from 5.0 to 6.0
> update to current naming scheme

- Expecto/Expecto.fs
- README.md
This PR introduces Obsolete attributes on deprecated functions. Ref: #429 
Also, we could perhaps remove them altogether on a future major release. What do you think?
> Add obsolete attribute on deprecated functions

- Expecto.Tests/FocusedTests.fs
- Expecto.Tests/Tests.fs
- Expecto/Expecto.fs
- README.md
- RELEASE_NOTES.md
This PR adds Theory/Parametrized test support.
Closes #438
> Add Theory Test Support

- Expecto/Flip.Expect.fs
also adjust the documentation of `Flip.Expect.stringContains` and `Flip.Expect.stringHasLength`
> Add missing Flip.Expect.hasLength

- README.md
testTheoryWithResult was removed because the same can be accomplished with testTheory. It cuts down the API surface considerably when considering focus, ignore, and async varients
> Update testTheoryWithResult example with testTheory equivalent

- paket.dependencies
quick PR to change expecto's `FSharp.Core` version requirement from `(= 7.0.200)` to ` (>= 7.0.200 && < 8.0.0)`
closes #458
> Loosen FSharp.Core version requirement

- Expecto.FsCheck3/Expecto.FsCheck3.fsproj
- paket.dependencies
This way we don't have to create a separate package. Should simplify adoption and trimming once FsCheck 3 reaches general release.
#450
> Update FsCheck3 support to release as a pre-release version of Expecto.FsCheck

- paket.dependencies
Replace #464. I updated recommended packaged, but whitebolt kept saying the new commit didn't warrant a rescan.
> Fix paket install (FsCheck3 versioning)

- RELEASE_NOTES.md
- build.fsx
`dotnet fake build -t pack` wasn't creating packages. Appears to be caused by a change in how temporary solution files work.
Also added support for packing the FsCheck3 pre-release version of `Expecto.FsCheck` and release notes for the changes to be released
> Fix pack build task

- README.md
I noticed some little typos in `README.md` while reading the documentation:
- it's => its
- .Net => .NET
- paket => Paket
- nuget => NuGet
This PR just fixes them.
> Some typos fixed

- Expecto.Tests/Tests.fs
- Expecto/Expecto.fs
- Expecto/Model.fs
- Expecto/Test.fs
- README.md
This PR introduces the missing `*testCaseTask` functions.
For context, I wanted to remove code similar to this from the codebases I work with: https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/a0fa8595acd4c4581e8e0cb8586e45c7a7f5a47b/tests/FsToolkit.ErrorHandling.TaskResult.Tests
> Add *testCaseTask functions

- .devcontainer/devcontainer.json
The default codespace for the repo couldn't build/run the code because it had the wrong version of .NET.
I set up a devcontainer.json to get the right .NET version and also install Ionide by default
> Add Codespace support

- Expecto.Tests/PerformanceTests.fs
- Expecto.Tests/Tests.fs
- Expecto/Expecto.fs
- build.fsx
Fix testCaseTask to accept a task, not an Async. Also fix test name conflicts.
I noticed this was causing build troubles when I went back to the interactive PR, so I fixed it.
> Fix testCaseTask to accept a task, not an Async

- Expecto.Tests/Tests.fs
- Expecto/Expecto.fs
- README.md
I.e. testTask and testCaseTask would start the task as soon as the test definition is created instead of when the test suite is run. This fixes a breaking change from how testTask used to work and a flaw of the new testCaseTask api. It is a breaking change to the testCaseTask api.
Thanks to @TheAngryByrd for [noticing this issue](https://github.com/haf/expecto/pull/484#issuecomment-2000168095) on pr
#484
> Fix immediate task execution when defining test cases

- Expecto.Tests/Tests.fs
- Expecto/Expecto.fs
refs #493 
Some testing to pin down where the issue is - not sure if this is the best apporach to fixing it, or if there are other types than strings that might have similar issues.
> Try to differentiate between null and empty strings in test theories

- Expecto.FsCheck/FsCheck.fs
- Expecto.FsCheck3/FsCheck3.fs
- Expecto.Tests.FsCheck3/FsCheck3Tests.fs
- Expecto.Tests/FsCheckTests.fs
- Expecto/Model.fs
- README.md
- RELEASE_NOTES.md
When using FsCheck3 it was impossible to use the replay seeds given in the failed test output because the config values only accepted `int32`, instead of `uint64`
> Fix unusable replay seed with FsCheck3

- .config/dotnet-tools.json
- .paket/Paket.Restore.targets
- paket.dependencies
When running the build, I got a number of 
```
Could not detect any platforms from 'net8.0' in XXXX
```
warnings in the build.
(There are a few of them in the Ci, e.g. https://github.com/haf/expecto/actions/runs/10391743404/job/28775360903#step:4:257)
Those can happen because Paket 7 doesn't know what .NET 8 is.
So - any thoughts about updating it to version 8 to try to fix the warnings?
> Update the fake-cli and Paket tools

- Expecto.BenchmarkDotNet.Tests/BenchmarkDotNetTests.fs
- Expecto.BenchmarkDotNet.Tests/Expecto.BenchmarkDotNet.Tests.fsproj
- build.fsx
I hadn't realised before, but it looks like the Expecto.BenchmarkDotNet.Tests test project isn't actually being built by the CI build - there are warnings in the build about not finding any projects to restore, e.g.
https://github.com/haf/expecto/actions/runs/10412005602/job/28836955136#step:4:355
And running it directly fails with an error about ```runTestsInAssembly``` not being found.
I don't know about the history of this project (maybe you don't actually want to run benchmarks during the CI  build?) - but it seems wrong to not at least compile it?
> Fix the build for Expecto.BenchmarkDotNet.Tests

- .github/workflows/build.yaml
I just noticed these 
in the CI builds and thought it might be useful to update the action to the latest version.
> Update the Github checkout/setup dotnet actions to v4 in the CI builds

- build.fsx
Refs https://github.com/haf/expecto/pull/506#issuecomment-2295282351
The extra tests don't take very long on my laptop, so lets see how the CI does
> Run Expecto.BenchmarkDotNet.Tests during the build

- Expecto/Expecto.Impl.fs
- Expecto/Expecto.fs
I tried running the Expecto library code through a few fsharp-analyzers, and got a few suggested changes.
These ones are from https://g-research.github.io/fsharp-analyzers/analyzers/VirtualCallAnalyzer.html where it suggests replacing Seq functions with explicit types when the collection types are fixed:
```
Expecto.Impl.fs(963,11): Warning GRA-VIRTUALCALL-001 : Consider replacing the call of Seq.tryFind with a function from the Array module to avoid the costs of virtual calls.
Expecto.Impl.fs(972,47): Warning GRA-VIRTUALCALL-001 : Consider replacing the call of Seq.find with a function from the Array module to avoid the costs of virtual calls.
Expecto.fs(546,12): Warning GRA-VIRTUALCALL-001 : Consider replacing the call of Seq.fold with a function from the List module to avoid the costs …
```
> A few fsharp-analyzers suggestions

- README.md
The installation command did not work for me in the fish shell on macOS. Adding the quotes fixed it.
I made the change using GitHub which unfortunately also applied some formatting or similar to an unrelated section.
Before:
```
dotnet new install Expecto.Template::*
fish: No matches for wildcard 'Expecto.Template::*'. See `help wildcards-globbing`.
dotnet new install Expecto.Template::*
^~~~~~~~~~~~~~~~~~^
```
After:
```
dotnet new install "Expecto.Template::*"
The following template packages will be installed:
Expecto.Template::*
...
```
> Fix template installation command for fish shell

- Expecto.Tests.CSharp/Tests.cs
- Expecto/CSharp.fs
- Expecto/Expecto.Impl.fs
- Expecto/Expecto.fs
- RELEASE_NOTES.md
Resolves #453
Separated out from #511
> Add `isTestSkipped` to `TestPrinters.beforeEach`
